name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lacolaco'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lacolaco'
      - run: yarn install --frozen-lockfile
      - run: yarn test --no-watch
