name: deploy to firebase hosting
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          access_token_scopes: 'email, openid, https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase'
          workload_identity_provider: 'projects/39289752392/locations/global/workloadIdentityPools/github-actions-deploy/providers/github-actions-deploy'
          service_account: 'github-actions-deploy@pokemon-tools-1e175.iam.gserviceaccount.com'
          create_credentials_file: true
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: npx firebase-tools deploy --project ${GCP_PROJECT} --only hosting
